// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkocGL2H7i-Ak0x1v1Gh56uKbpW8gKebs',
    appId: '1:368420281321:web:80f76bb5fd0daaa0f30978',
    messagingSenderId: '368420281321',
    projectId: 'govtest-72290',
    authDomain: 'govtest-72290.firebaseapp.com',
    storageBucket: 'govtest-72290.appspot.com',
    measurementId: 'G-4YLTBMFP77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJocdyvfOTnRVDg4E7sMfDuub5Xm47Y3E',
    appId: '1:368420281321:android:73565374b6134ebef30978',
    messagingSenderId: '368420281321',
    projectId: 'govtest-72290',
    storageBucket: 'govtest-72290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NfSbRwSTlnlV44e_SEPd0kHXwLSpMuE',
    appId: '1:368420281321:ios:8b07ad219c917efaf30978',
    messagingSenderId: '368420281321',
    projectId: 'govtest-72290',
    storageBucket: 'govtest-72290.appspot.com',
    androidClientId: '368420281321-4pffvc138qtl1f168ql07j09a5bq2b16.apps.googleusercontent.com',
    iosClientId: '368420281321-s8gv19c81v5r3ocrnro6tl89th9fpmrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.govtestGeneral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NfSbRwSTlnlV44e_SEPd0kHXwLSpMuE',
    appId: '1:368420281321:ios:8b07ad219c917efaf30978',
    messagingSenderId: '368420281321',
    projectId: 'govtest-72290',
    storageBucket: 'govtest-72290.appspot.com',
    androidClientId: '368420281321-4pffvc138qtl1f168ql07j09a5bq2b16.apps.googleusercontent.com',
    iosClientId: '368420281321-s8gv19c81v5r3ocrnro6tl89th9fpmrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.govtestGeneral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkocGL2H7i-Ak0x1v1Gh56uKbpW8gKebs',
    appId: '1:368420281321:web:e89b1222b5ba33abf30978',
    messagingSenderId: '368420281321',
    projectId: 'govtest-72290',
    authDomain: 'govtest-72290.firebaseapp.com',
    storageBucket: 'govtest-72290.appspot.com',
    measurementId: 'G-71RVG7YLP1',
  );
}
